name: Deploy Web App
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
          tags: tag:ci

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: portfolio
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/my-web-app
            git pull origin main
            docker build -t my-site .
            docker stop test-container || true
            docker rm test-container || true
            docker run -d -p 127.0.0.1:8080:80 --name test-container my-site
